# https://docs.github.com/en/actions/guides/publishing-docker-images

name: Publish Docker image

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkt out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          # Username of the user who pushed
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: wgslr/trunkless-whiteboard/app-image
          tag_with_ref: true
